### PR TITLE
Update decision_functions.R

### PR DESCRIPTION
**Pull request by peteowen1**
Include decay function rather than step function of multiplying by either 0.9 or 0.

(e.g. Zuerlein 60yd FG during 2021_01_DAL_TB was given a 36% chance to be made, but if it was 1 yard further out the bot would've assigned a ~0% probability which is obviously wrong. 
New method would've given a ~28% chance at 60 yards, ~24% chance from 61 yards)

Still hacky but a better form of hacky. 

Ideally plan to create player-based models in next commit. 
Would be made easily possible if kicker/punter are available to be included in: https://github.com/nflverse/nfldata/blob/master/data/games.rds

### CODE REVIEW

**Comment by guga31bb** [comment]
I'm a bit nervous about adding player-based models because it adds a layer of complexity that would be pretty tough for live games (because the ESPN API doesn't provide much about kickers)

**Comment by peteowen1** [comment]
Can probably close this now that something similar has been done here
https://github.com/nflverse/nfl4th/commit/ef6acd4da5c776fdddd7c7b30b084c61619b1897

**Comment by guga31bb** [comment]
Yes I looked at your code before revising- thanks, should have done something about this years ago...

**Comment by peteowen1** [comment]
No worries! And yeah new version is definitely improved, worth the change

**Pull request closed without merging**
